# SPDX-License-Identifier: GPL-3.0-or-later
#
# PyInstaller spec for VoxKit — one-directory bundle for Windows and Linux.
#
# Usage (from repo root, after `pip install pyinstaller`):
#   pyinstaller voxkit.spec
#
# Output:
#   dist/voxkit/         one-directory bundle
#   dist/voxkit/voxkit   (Linux) or dist/voxkit/voxkit.exe  (Windows)
#
# The bundle includes:
#   - All Python runtime modules (frozen into a single .pkg archive)
#   - PySide6 Qt libraries and plugins
#   - onnxruntime shared libraries and execution-provider plugins
#   - models/  — ONNX model files (Q18; bundled alongside the executable)
#
# voxkit.eval is excluded — it is dev-only and not part of the shipped app.
# PyInstaller version ≥ 6.0 is required (PySide6 hook maturity).

from pathlib import Path
from PyInstaller.utils.hooks import collect_all, collect_submodules

ROOT = Path(SPECPATH)

# ---------------------------------------------------------------
# Collect packages whose data / binaries cannot be found statically.
# collect_all returns (datas, binaries, hiddenimports) tuples.
# ---------------------------------------------------------------
pyside6_datas,    pyside6_binaries,    pyside6_hiddenimports    = collect_all("PySide6")
ort_datas,        ort_binaries,        ort_hiddenimports        = collect_all("onnxruntime")
sklearn_hidden = collect_submodules("sklearn")
scipy_hidden   = collect_submodules("scipy")

a = Analysis(
    [str(ROOT / "src" / "voxkit" / "__main__.py")],
    pathex=[str(ROOT / "src")],
    binaries=pyside6_binaries + ort_binaries,
    datas=[
        # ONNX model files.  At runtime the app locates them relative to
        # sys.executable so this destination must be "models".
        # Includes onset_cnn.onnx (generated by scripts/train_onset_detector.py)
        # and the embedding substrate models.
        (str(ROOT / "models"), "models"),
        *pyside6_datas,
        *ort_datas,
    ],
    hiddenimports=[
        # onnxruntime execution providers are registered by name at runtime.
        "onnxruntime.backend",
        "onnxruntime.capi",
        *ort_hiddenimports,
        # PySide6 modules loaded dynamically by Qt (signal/slot machinery,
        # QML engine, multimedia — include only what the app actually uses).
        *pyside6_hiddenimports,
        # scikit-learn Cython extensions are not discovered by static analysis.
        *sklearn_hidden,
        # scipy sparse solvers used by sklearn's saga LR solver.
        *scipy_hidden,
        # librosa sub-packages loaded lazily.
        "librosa.core.audio",
        "librosa.core.spectrum",
        "librosa.feature",
        "librosa.filters",
        "librosa.util",
        # torchaudio (required for BEATs fbank pre-processing).
        "torchaudio.compliance.kaldi",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Dev / eval tooling — not part of the shipped application.
        "voxkit.eval",
        "pytest",
        "IPython",
        "matplotlib",
        "notebook",
        "numba",
        # PyInstaller itself must not end up inside its own bundle.
        "PyInstaller",
    ],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="voxkit",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,   # strip=True can break PySide6 on Linux; keep False.
    upx=True,
    console=False,   # GUI application; suppresses the console window on Windows.
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[
        # UPX can corrupt some Qt/PySide6 shared libraries.
        "Qt6Core*",
        "Qt6Gui*",
        "Qt6Widgets*",
        "Qt6Multimedia*",
        "libQt6*",
    ],
    name="voxkit",
)
